### PR TITLE
chore: rebrand AdminBro to AdminJS

### PR DESCRIPTION
**Pull request by Andrianka**
This commit is a part of AdminBro to AdminJS rebranding process.

BREAKING CHANGE: AdminBro has been rebranded to AdminJS. All package and repository names had been updated.

1. Update your dependencies to use new `adminjs` packages.
- `admin-bro` -> `adminjs` for the core package
- `@admin-bro/<package name>` -> `@adminjs/<package name>` for other modules
2. Update your custom CSS classes:
- `.admin-bro_<component name>` -> `.adminjs_<component name>` (example: `.adminjs_Box`)
3. Search your project for `admin-bro` occurrences - most likely they will have to be updated to `adminjs`

### CODE REVIEW

**Review by danklewicz-swb — APPROVED** [review]

**Comment by RJason13** [comment]
Hi, I'm really happy with adminjs and am waiting for this update. I am wondering if there is an estimation of when will this update be finished and published to npm?

**Comment by dziraf** [comment]
@RJason13 We need to review this package before publishing because it looks like there are some conflicts between it and the newest version of the core. Can't give you an ETA right now, you may want to use `admin-bro` packages instead of `adminjs` until then.

**Comment by RJason13** [comment]
@dziraf I see, thank you very much for the information.

**Comment by khlevon** [comment]
Hi @dziraf . Can we help with something to publish a new version of this package?

**Comment by revnode** [comment]
@dziraf It would be really nice to get this and/or https://github.com/SoftwareBrothers/adminjs-koa/pull/5 merged in and published. As of right now, those using koa are stuck on an older version without the rebrand. Happy to help with anything.

**Pull request merged**
